---
# @author Team 63, Melbourne, 2023
# Hanying Li (1181148) Haichi Long (1079593) Ji Feng (1412053)
# Jiayao Lu (1079059) Xinlin Li (1068093)

- name: Create security groups
  openstack.cloud.security_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
  loop: "{{ security_groups }}"

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: "{{ sg_names|default([]) + [ item.name ] }}"
  loop: "{{ security_groups }}"

- name: Print out debugging information
  ansible.builtin.debug:
    msg: "Security group(s) {{ sg_names }} have been created."

- name: Add security group rules to the security groups
  openstack.cloud.security_group_rule:
    security_group: "{{ item.0.name }}"
    protocol: "{{ item.1.protocol }}"
    port_range_min: "{{ item.1.port_range_min }}"
    port_range_max: "{{ item.1.port_range_max }}"
    remote_ip_prefix: "{{ item.1.remote_ip_prefix }}"
    state: present
  loop: "{{ security_groups|subelements('rules') }}"